# Generated by Django 3.1 on 2020-10-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201005_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
