# Generated by Django 3.1 on 2020-10-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201005_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='lastname',
        ),
        migrations.AddField(
            model_name='callback',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
