# Generated by Django 3.1 on 2020-10-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mopup_round1_round2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, db_column='COLLEGE', max_length=100, null=True)),
                ('region', models.CharField(blank=True, db_column='REGION', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=20, null=True)),
                ('course', models.CharField(blank=True, db_column='COURSE', max_length=10, null=True)),
                ('quota', models.CharField(blank=True, db_column='QUOTA', max_length=10, null=True)),
                ('gn_or', models.IntegerField(blank=True, db_column='GN_OR', null=True)),
                ('gn_cr', models.IntegerField(blank=True, db_column='GN_CR', null=True)),
                ('gn_seats', models.IntegerField(blank=True, db_column='GN_SEATS', null=True)),
                ('obc_or', models.IntegerField(blank=True, db_column='OBC_OR', null=True)),
                ('obc_cr', models.IntegerField(blank=True, db_column='OBC_CR', null=True)),
                ('obc_seats', models.IntegerField(blank=True, db_column='OBC_SEATS', null=True)),
                ('sc_or', models.IntegerField(blank=True, db_column='SC_OR', null=True)),
                ('sc_cr', models.IntegerField(blank=True, db_column='SC_CR', null=True)),
                ('sc_seats', models.IntegerField(blank=True, db_column='SC_SEATS', null=True)),
                ('st_or', models.IntegerField(blank=True, db_column='ST_OR', null=True)),
                ('st_cr', models.IntegerField(blank=True, db_column='ST_CR', null=True)),
                ('st_seats', models.IntegerField(blank=True, db_column='ST_SEATS', null=True)),
                ('gn_pwd_or', models.IntegerField(blank=True, db_column='GN_PwD_OR', null=True)),
                ('gn_pwd_cr', models.IntegerField(blank=True, db_column='GN_PwD_CR', null=True)),
                ('gn_pwd_seats', models.IntegerField(blank=True, db_column='GN_PwD_SEATS', null=True)),
                ('obc_pwd_or', models.IntegerField(blank=True, db_column='OBC_PwD_OR', null=True)),
                ('obc_pwd_cr', models.IntegerField(blank=True, db_column='OBC_PwD_CR', null=True)),
                ('obc_pwd_seats', models.IntegerField(blank=True, db_column='OBC_PwD_SEATS', null=True)),
                ('sc_pwd_or', models.IntegerField(blank=True, db_column='SC_PwD_OR', null=True)),
                ('sc_pwd_cr', models.IntegerField(blank=True, db_column='SC_PwD_CR', null=True)),
                ('sc_pwd_seats', models.IntegerField(blank=True, db_column='SC_PwD_SEATS', null=True)),
                ('st_pwd_or', models.IntegerField(blank=True, db_column='ST_PwD_OR', null=True)),
                ('st_pwd_cr', models.IntegerField(blank=True, db_column='ST_PwD_CR', null=True)),
                ('st_pwd_seats', models.IntegerField(blank=True, db_column='ST_PwD_SEATS', null=True)),
            ],
        ),
    ]
