# Generated by Django 3.1 on 2020-10-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201012_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mopup',
            name='sc_pwd_cr',
        ),
        migrations.RemoveField(
            model_name='mopup',
            name='sc_pwd_or',
        ),
        migrations.RemoveField(
            model_name='mopup',
            name='sc_pwd_seats',
        ),
        migrations.RemoveField(
            model_name='mopup',
            name='st_pwd_cr',
        ),
        migrations.RemoveField(
            model_name='mopup',
            name='st_pwd_or',
        ),
        migrations.RemoveField(
            model_name='mopup',
            name='st_pwd_seats',
        ),
        migrations.AddField(
            model_name='mopup',
            name='ew_no_cr',
            field=models.IntegerField(blank=True, db_column='EW_NO_CR', null=True),
        ),
        migrations.AddField(
            model_name='mopup',
            name='ew_no_or',
            field=models.IntegerField(blank=True, db_column='EW_NO_OR', null=True),
        ),
        migrations.AddField(
            model_name='mopup',
            name='ew_no_seats',
            field=models.IntegerField(blank=True, db_column='EW_NO_SEATS', null=True),
        ),
        migrations.AddField(
            model_name='round2',
            name='ewno_cr',
            field=models.IntegerField(blank=True, db_column='EWNO_CR', null=True),
        ),
        migrations.AddField(
            model_name='round2',
            name='ewno_or',
            field=models.IntegerField(blank=True, db_column='EWNO_OR', null=True),
        ),
        migrations.AddField(
            model_name='round2',
            name='ewno_seats',
            field=models.IntegerField(blank=True, db_column='EWNO_SEATS', null=True),
        ),
        migrations.AlterField(
            model_name='mopup',
            name='state',
            field=models.TextField(blank=True, db_column='STATE', max_length=25, null=True),
        ),
    ]
