# Generated by Django 3.1 on 2020-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201012_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_predictor',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
