# Generated by Django 3.1 on 2020-10-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201012_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mopup',
            name='ew_no_cr',
        ),
        migrations.RemoveField(
            model_name='mopup',
            name='ew_no_or',
        ),
        migrations.RemoveField(
            model_name='mopup',
            name='ew_no_seats',
        ),
        migrations.RemoveField(
            model_name='round2',
            name='ewno_cr',
        ),
        migrations.RemoveField(
            model_name='round2',
            name='ewno_or',
        ),
        migrations.RemoveField(
            model_name='round2',
            name='ewno_seats',
        ),
        migrations.AddField(
            model_name='mopup',
            name='ew_cr',
            field=models.IntegerField(blank=True, db_column='EW_CR', null=True),
        ),
        migrations.AddField(
            model_name='mopup',
            name='ew_or',
            field=models.IntegerField(blank=True, db_column='EW_OR', null=True),
        ),
        migrations.AddField(
            model_name='mopup',
            name='ew_seats',
            field=models.IntegerField(blank=True, db_column='EW_SEATS', null=True),
        ),
        migrations.AddField(
            model_name='round2',
            name='ew_cr',
            field=models.IntegerField(blank=True, db_column='EW_CR', null=True),
        ),
        migrations.AddField(
            model_name='round2',
            name='ew_or',
            field=models.IntegerField(blank=True, db_column='EW_OR', null=True),
        ),
        migrations.AddField(
            model_name='round2',
            name='ew_seats',
            field=models.IntegerField(blank=True, db_column='EW_SEATS', null=True),
        ),
    ]
